#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Project: AI Startup Landing Page (Twinkle.ai)

set -e

echo "========================================"
echo "Starting Development Environment"
echo "AI Startup Landing Page (Twinkle.ai)"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root directory
PROJECT_DIR="/Volumes/Software Engineer/AI Engineer/Auto Claude/ai-saas-landing-page"

# Change to project directory
cd "$PROJECT_DIR"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed. Please install Node.js 18+${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js $(node -v)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm $(npm -v)${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

if [ -f "package.json" ]; then
    npm install
    echo -e "${GREEN}✓ Dependencies installed${NC}"
else
    echo -e "${YELLOW}⚠ package.json not found - project scaffolding needed${NC}"
    echo "Run implementation phase 1 first to create project structure"
fi

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo "Starting development server..."

if [ -f "package.json" ] && grep -q '"dev"' package.json; then
    # Start Vite dev server
    npm run dev &
    DEV_PID=$!

    # Wait for service to be ready
    wait_for_service 5173 "Frontend (Vite)"

    echo ""
    echo "========================================"
    echo -e "${GREEN}Environment Ready!${NC}"
    echo "========================================"
    echo ""
    echo "Services:"
    echo "  Frontend: http://localhost:5173"
    echo ""
    echo "Press Ctrl+C to stop the development server"
    echo ""

    # Keep script running
    wait $DEV_PID
else
    echo -e "${YELLOW}⚠ Dev script not found - project scaffolding needed${NC}"
    echo ""
    echo "To scaffold the project, the coder agent will:"
    echo "  1. Create Vite + React + TypeScript project"
    echo "  2. Install Tailwind CSS"
    echo "  3. Set up all configuration files"
    echo ""
    echo "After scaffolding, run this script again to start development."
fi
